name: main

on:
  push:
    branches: [ feature/workflow ]
  pull_request:
    branches: [ feature/workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: "src/mapline.web"

    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: "src/mapline.web"

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: "src/mapline.web"

    - name: Publish
      run: dotnet publish --no-build --verbosity normal
      working-directory: "src/mapline.web"
